name: 20220913_pyhep2022
channels:
  - conda-forge
dependencies:
  - python>=3.8
  # Setting recent versions to make the conda solve faster
  - numpy>=1.16
  - pandas>=0.24
  - attrs>=19.2
  - pip>19.0
  - jupyterlab>=1.0
  - graphviz>=0.12.0
  - lark-parser>=0.11.0
  - plumbum>=1.6.9
  - tabulate
  - hepunits==2.2.1
  - particle==0.20.1
  - RISE
  - decaylanguage==0.14.2
